name: Deploy to LocalStack

on: 
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack-pro:latest
        ports: 
          - 4566:4566
          - 4510-4559:4510-4559
        env:
          SERVICES: "cognito-idp,sqs,lambda,iam"
          DEBUG: "1"
          DATA_DIR: "/tmp/localstack/data"
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v3

      - name: Instalar Dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Inicializar Terraform
        working-directory: ./infrastructure
        run: |
          terraform init

      - name: Aplicar Terraform
        working-directory: ./infrastructure
        run: |
          terraform apply -auto-approve

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "test"  # LocalStack usa essas credenciais fictícias
          aws-secret-access-key: "test"  # LocalStack usa essas credenciais fictícias
          aws-region: us-east-1
          aws-session-token: "null"  # Remover token ou passar "null"
          
        run: |
          zip lambda.zip lambda/lambda_function.py
          aws --endpoint-url=http://localhost:4566 lambda create-function \
            --function-name check-user-by-cpf \
            --runtime python3.9 \
            --role arn:aws:iam::000000000000:role/lambda-ex \
            --handler lambda_function.lambda_handler \
            --zip-file fileb://lambda.zip
            --region us-west-1
