name: Deploy to LocalStack

on: 
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack-pro:latest
        ports: 
          - 4566:4566
          - 4510-4559:4510-4559
        env:
          SERVICES: "cognito-idp,sqs,lambda,iam,apigateway"
          DEBUG: "1"
          DATA_DIR: "/tmp/localstack/data"
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          LAMBDA_EXECUTOR: docker
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"

    env: 
        AWS_ACCESS_KEY_ID: "test"
        AWS_SECRET_ACCESS_KEY: "test"
        AWS_REGION: "us-east-1"
        AWS_DEFAULT_REGION: "us-east-1"

    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v3

      - name: Instalar Dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Inicializar Terraform
        working-directory: ./infrastructure
        run: |
          terraform init

      - name: Aplicar Terraform
        working-directory: ./infrastructure
        run: |
          terraform apply -auto-approve

      - name: Criar Usuário
        run: |
          aws --endpoint-url=http://localhost:4566 cognito-idp admin-create-user \
          --user-pool-id $(aws --endpoint-url=http://localhost:4566 cognito-idp list-user-pools --max-results 10 --query "UserPools[?Name=='localstack-user-pool'].Id" --output text) \
          --username "12345678900" \
          --user-attributes Name=email,Value=teste@example.com

      - name: Invocar a Lambda
        run: |
          aws --endpoint-url=http://localhost:4566 lambda invoke \
            --function-name check-user-by-cpf \
            --payload ewogICAgImNwZiI6ICIxMjM0NTY3ODkwMCIKICAgIAp9 \
            output.json
          cat output.json
      - name: Buscar usuário com a API GATEWAY
        run: |
          curl -X POST http://localhost:4566/restapis/$(aws apigateway get-rest-apis --endpoint-url=http://localhost:4566 --query "items[0].id" --output text)/ /
          prod/_user_request_/user-check   -H "Content-Type: application/json"   -d '{"cpf": "12345678900"}'
          